/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Color: typeof import('./src/components/color/index.vue')['default']
    ProductCard: typeof import('./src/components/product-card/index.vue')['default']
    Result: typeof import('./src/components/result/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Thumbnail: typeof import('./src/components/thumbnail/index.vue')['default']
    Trend: typeof import('./src/components/trend/index.vue')['default']
  }
}
